// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ModalPresentationTest.ViewControllers;

public partial class PopoverViewController : UIViewController
{
	public PopoverViewController(IntPtr handle) : base(handle)
	{
	}
}